# Generated by Django 3.2.2 on 2021-05-11 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CVData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('summary', models.TextField(max_length=2000)),
                ('degree', models.CharField(max_length=100)),
                ('university', models.CharField(max_length=200)),
                ('previous_jobs', models.TextField(max_length=2000)),
                ('skills', models.TextField(max_length=2000)),
            ],
        ),
    ]
