# Generated by Django 3.2.2 on 2021-05-11 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CVData',
            new_name='Profile',
        ),
    ]
